2014/12/03 05:14:26 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\newOpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:107
Stack trace:
#0 [internal function]: IssuesController->actionAdd('')
#1 C:\newOpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\newOpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add/id')
#8 C:\newOpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\newOpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/id/
---
2014/12/03 05:14:32 [error] [exception.CHttpException.404] exception 'CHttpException' in C:\newOpenServer\domains\ybugs.local\protected\controllers\IssuesController.php:107
Stack trace:
#0 [internal function]: IssuesController->actionAdd(NULL)
#1 C:\newOpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(IssuesController), Array)
#2 C:\newOpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(IssuesController), Object(ReflectionMethod), Array)
#3 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#4 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#5 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#6 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('add')
#7 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('issues/add')
#8 C:\newOpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#9 C:\newOpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#10 {main}
REQUEST_URI=/issues/add/
---
2014/12/03 22:08:50 [error] [exception.CException] exception 'CException' with message 'ExtUserRoles and its behaviors do not have a method or closure named "getUseRole".' in C:\newOpenServer\domains\ybugs.local\framework\base\CComponent.php:266
Stack trace:
#0 C:\newOpenServer\domains\ybugs.local\framework\db\ar\CActiveRecord.php(227): CComponent->__call('getUseRole', Array)
#1 C:\newOpenServer\domains\ybugs.local\protected\controllers\UsersController.php(110): CActiveRecord->__call('getUseRole', Array)
#2 C:\newOpenServer\domains\ybugs.local\protected\controllers\UsersController.php(110): ExtUserRoles->getUseRole('1')
#3 [internal function]: UsersController->actionAddPrj('1')
#4 C:\newOpenServer\domains\ybugs.local\framework\web\actions\CAction.php(108): ReflectionMethod->invokeArgs(Object(UsersController), Array)
#5 C:\newOpenServer\domains\ybugs.local\framework\web\actions\CInlineAction.php(47): CAction->runWithParamsInternal(Object(UsersController), Object(ReflectionMethod), Array)
#6 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(308): CInlineAction->runWithParams(Array)
#7 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(286): CController->runAction(Object(CInlineAction))
#8 C:\newOpenServer\domains\ybugs.local\framework\web\CController.php(265): CController->runActionWithFilters(Object(CInlineAction), Array)
#9 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(282): CController->run('addprj')
#10 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('users/addprj')
#11 C:\newOpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#12 C:\newOpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#13 {main}
REQUEST_URI=/en/users/addprj/1
HTTP_REFERER=http://ybugs.local/en/users/list
---
2014/12/03 22:13:31 [error] [exception.CHttpException.404] exception 'CHttpException' with message 'Unable to resolve the request "user/list".' in C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php:286
Stack trace:
#0 C:\newOpenServer\domains\ybugs.local\framework\web\CWebApplication.php(141): CWebApplication->runController('user/list')
#1 C:\newOpenServer\domains\ybugs.local\framework\base\CApplication.php(180): CWebApplication->processRequest()
#2 C:\newOpenServer\domains\ybugs.local\index.php(13): CApplication->run()
#3 {main}
REQUEST_URI=/en/user/list
HTTP_REFERER=http://ybugs.local/en/users/addprj/1
---
